### ISSUE TITLE
ImportError: DLL load failed while importing _cext: 找不到指定的模块?

### ISSUE THREAD

**Issue by umeitime** [ngc660sec/NGCBot#70]
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from BotServer.MainServer import MainServer
  File "F:\wxbot\NGCBot\BotServer\MainServer.py", line 2, in <module>
    from BotServer.MsgHandleServer.RoomMsgHandle import RoomMsgHandle
  File "F:\wxbot\NGCBot\BotServer\MsgHandleServer\RoomMsgHandle.py", line 3, in <module>
    from BotServer.BotFunction.HappyFunction import HappyFunction
  File "F:\wxbot\NGCBot\BotServer\BotFunction\HappyFunction.py", line 2, in <module>
    from ApiServer.ApiMainServer import ApiMainServer
  File "F:\wxbot\NGCBot\ApiServer\ApiMainServer.py", line 2, in <module>
    import ApiServer.pluginServer as Ps
  File "F:\wxbot\NGCBot\ApiServer\pluginServer\__init__.py", line 1, in <module>
    from ApiServer.pluginServer.HappyApi import HappyApi
  File "F:\wxbot\NGCBot\ApiServer\pluginServer\HappyApi.py", line 1, in <module>
    from meme_generator import get_meme, get_meme_keys
  File "C:\Users\june\AppData\Local\Programs\Python\Python38\lib\site-packages\meme_generator\__init__.py", line 4, in <module>
    from meme_generator.manager import add_meme as add_meme
  File "C:\Users\june\AppData\Local\Programs\Python\Python38\lib\site-packages\meme_generator\manager.py", line 10, in <module>
    from .meme import Meme, MemeArgsType, MemeFunction, MemeParamsType
  File "C:\Users\june\AppData\Local\Programs\Python\Python38\lib\site-packages\meme_generator\meme.py", line 22, in <module>
    from pil_utils import BuildImage
  File "C:\Users\june\AppData\Local\Programs\Python\Python38\lib\site-packages\pil_utils\__init__.py", line 1, in <module>
    from .build_image import BuildImage as BuildImage
  File "C:\Users\june\AppData\Local\Programs\Python\Python38\lib\site-packages\pil_utils\build_image.py", line 15, in <module>
    from .text2image import Text2Image
  File "C:\Users\june\AppData\Local\Programs\Python\Python38\lib\site-packages\pil_utils\text2image.py", line 11, in <module>
    from .fonts import Font, get_proper_font
  File "C:\Users\june\AppData\Local\Programs\Python\Python38\lib\site-packages\pil_utils\fonts.py", line 6, in <module>
    from matplotlib.font_manager import FontProperties, fontManager
  File "C:\Users\june\AppData\Local\Programs\Python\Python38\lib\site-packages\matplotlib\__init__.py", line 255, in <module>
    _check_versions()
  File "C:\Users\june\AppData\Local\Programs\Python\Python38\lib\site-packages\matplotlib\__init__.py", line 249, in _check_versions
    module = importlib.import_module(modname)
  File "C:\Users\june\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\june\AppData\Local\Programs\Python\Python38\lib\site-packages\kiwisolver\__init__.py", line 8, in <module>
    from ._cext import (
ImportError: DLL load failed while importing _cext: 找不到指定的模块。

**Comment by ngc660sec** [comment]
提供系统相关信息

**Comment by fuli66** [comment]
设备名称	DESKTOP-ETGHK03
处理器	Intel(R) N100   806 MHz
机带 RAM	8.00 GB
设备 ID	9BD0C37E-E782-490B-BB74-BE30784BD387
产品 ID	00331-10000-00001-AA730
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	没有可用于此显示器的笔或触控输入

版本	Windows 10 专业版
版本号	22H2
安装日期	‎2024/‎11/‎9
操作系统内部版本	19045.5011
体验	Windows Feature Experience Pack 1000.19060.1000.0

**Comment by fuli66** [comment]
设备名称 DESKTOP-ETGHK03
处理器 Intel(R) N100 806 MHz
机带 RAM 8.00 GB
设备 ID 9BD0C37E-E782-490B-BB74-BE30784BD387
产品 ID 00331-10000-00001-AA730
系统类型 64 位操作系统, 基于 x64 的处理器
笔和触控 没有可用于此显示器的笔或触控输入

版本 Windows 10 专业版
版本号 22H2
安装日期 ‎2024/‎11/‎9
操作系统内部版本 19045.5011
体验 Windows Feature Experience Pack 1000.19060.1000.0

**Comment by fuli66** [comment]
> > 设备名称 DESKTOP-ETGHK03 处理器 Intel(R) N100 806 MHz 机带 RAM 8.00 GB 设备 ID 9BD0C37E-E782-490B-BB74-BE30784BD387 产品 ID 00331-10000-00001-AA730 系统类型 64 位操作系统, 基于 x64 的处理器 笔和触控 没有可用于此显示器的笔或触控输入
> > 版本 Windows 10 专业版 版本号 22H2 安装日期 ‎2024/‎11/‎9 操作系统内部版本 19045.5011 体验 Windows Feature Experience Pack 1000.19060.1000.0
> 
> python 版本是多少

从你这里下载的3.8.0

**Comment by ngc660sec** [comment]
> > > 设备名称 DESKTOP-ETGHK03 处理器 Intel(R) N100 806 MHz 机带 RAM 8.00 GB 设备 ID 9BD0C37E-E782-490B-BB74-BE30784BD387 产品 ID 00331-10000-00001-AA730 系统类型 64 位操作系统, 基于 x64 的处理器 笔和触控 没有可用于此显示器的笔或触控输入
> > > 版本 Windows 10 专业版 版本号 22H2 安装日期 ‎2024/‎11/‎9 操作系统内部版本 19045.5011 体验 Windows Feature Experience Pack 1000.19060.1000.0
> > 
> > 
> > python 版本是多少
> 
> 从你这里下载的3.8.0

微信版本检查一下

**Comment by fuli66** [comment]
> > > > 设备名称 DESKTOP-ETGHK03 处理器 Intel(R) N100 806 MHz 机带 RAM 8.00 GB 设备 ID 9BD0C37E-E782-490B-BB74-BE30784BD387 产品 ID 00331-10000-00001-AA730 系统类型 64 位操作系统, 基于 x64 的处理器 笔和触控 没有可用于此显示器的笔或触控输入
> > > > 版本 Windows 10 专业版 版本号 22H2 安装日期 ‎2024/‎11/‎9 操作系统内部版本 19045.5011 体验 Windows Feature Experience Pack 1000.19060.1000.0
> > > 
> > > 
> > > python 版本是多少
> > 
> > 
> > 从你这里下载的3.8.0
> 
> 微信版本检查一下

39.2.4.0 你这边下载的

**Comment by ngc660sec** [comment]
> > > > > 设备名称 DESKTOP-ETGHK03 处理器 Intel(R) N100 806 MHz 机带 RAM 8.00 GB 设备 ID 9BD0C37E-E782-490B-BB74-BE30784BD387 产品 ID 00331-10000-00001-AA730 系统类型 64 位操作系统, 基于 x64 的处理器 笔和触控 没有可用于此显示器的笔或触控输入
> > > > > 版本 Windows 10 专业版 版本号 22H2 安装日期 ‎2024/‎11/‎9 操作系统内部版本 19045.5011 体验 Windows Feature Experience Pack 1000.19060.1000.0
> > > > 
> > > > 
> > > > python 版本是多少
> > > 
> > > 
> > > 从你这里下载的3.8.0
> > 
> > 
> > 微信版本检查一下
> 
> 39.2.4.0 你这边下载的

截图 一般都是微信版本不对

**Comment by wenfa1999** [comment]
同样的问题，请帮忙看看
![image](https://github.com/user-attachments/assets/3798e0c6-7fe2-49d0-b705-c50605c873e3)

python版本: `Python 3.8.10`
微信版本：`微信 3.9.10.27`
系统信息：
```
设备名称	DESKTOP-KULS71G
处理器	13th Gen Intel(R) Core(TM) i5-13600K   3.49 GHz
机带 RAM	16.0 GB (3.80 GB 可用)
设备 ID	
产品 ID	
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	没有可用于此显示器的笔或触控输入

版本	Windows 10 专业版
版本号	22H2
安装日期	‎2024/‎11/‎17
操作系统内部版本	19045.5131
体验	Windows Feature Experience Pack 1000.19060.1000.0
```

执行`python main.py`报错：
```powershell
python main.py
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from BotServer.MainServer import MainServer
  File "C:\Users\GWF\Desktop\NGCBot\BotServer\MainServer.py", line 2, in <module>
    from BotServer.MsgHandleServer.RoomMsgHandle import RoomMsgHandle
  File "C:\Users\GWF\Desktop\NGCBot\BotServer\MsgHandleServer\RoomMsgHandle.py", line 3, in <module>
    from BotServer.BotFunction.HappyFunction import HappyFunction
  File "C:\Users\GWF\Desktop\NGCBot\BotServer\BotFunction\HappyFunction.py", line 2, in <module>
    from ApiServer.ApiMainServer import ApiMainServer
  File "C:\Users\GWF\Desktop\NGCBot\ApiServer\ApiMainServer.py", line 2, in <module>
    import ApiServer.pluginServer as Ps
  File "C:\Users\GWF\Desktop\NGCBot\ApiServer\pluginServer\__init__.py", line 1, in <module>
    from ApiServer.pluginServer.HappyApi import HappyApi
  File "C:\Users\GWF\Desktop\NGCBot\ApiServer\pluginServer\HappyApi.py", line 1, in <module>
    from meme_generator import get_meme, get_meme_keys
  File "C:\Users\GWF\AppData\Local\Programs\Python\Python38\lib\site-packages\meme_generator\__init__.py", line 4, in <module>
    from meme_generator.manager import add_meme as add_meme
  File "C:\Users\GWF\AppData\Local\Programs\Python\Python38\lib\site-packages\meme_generator\manager.py", line 10, in <module>
    from .meme import Meme, MemeArgsType, MemeFunction, MemeParamsType
  File "C:\Users\GWF\AppData\Local\Programs\Python\Python38\lib\site-packages\meme_generator\meme.py", line 22, in <module>
    from pil_utils import BuildImage
  File "C:\Users\GWF\AppData\Local\Programs\Python\Python38\lib\site-packages\pil_utils\__init__.py", line 1, in <module>
    from .build_image import BuildImage as BuildImage
  File "C:\Users\GF\AppData\Local\Programs\Python\Python38\lib\site-packages\pil_utils\build_image.py", line 15, in <module>
    from .text2image import Text2Image
  File "C:\Users\GWF\AppData\Local\Programs\Python\Python38\lib\site-packages\pil_utils\text2image.py", line 11, in <module>
    from .fonts import Font, get_proper_font
  File "C:\Users\GWF\AppData\Local\Programs\Python\Python38\lib\site-packages\pil_utils\fonts.py", line 6, in <module>
    from matplotlib.font_manager import FontProperties, fontManager
  File "C:\Users\GWF\AppData\Local\Programs\Python\Python38\lib\site-packages\matplotlib\__init__.py", line 255, in <module>
    _check_versions()
  File "C:\Users\GWF\AppData\Local\Programs\Python\Python38\lib\site-packages\matplotlib\__init__.py", line 249, in _check_versions
    module = importlib.import_module(modname)
  File "C:\Users\GWF\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\GWF\AppData\Local\Programs\Python\Python38\lib\site-packages\kiwisolver\__init__.py", line 8, in <module>
    from ._cext import (
ImportError: DLL load failed while importing _cext: 找不到指定的模块。
```

**Comment by NetSafeDaSheng** [comment]
If the file "C: \ Users \ GWF \ AppData \ Local \ Programs \ Python \ Python 38 \ lib \ site packages \ kiwisolver \ __init__. py" appears, line 8, in<module>
from ._cext import (
ImportError: DLL load failed while importing _cext: The specified module cannot be found.
This error occurs. You can try installing this library to fix the problem
https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by ngc660sec** [comment]
> > If the file "C: \ Users \ GWF \ AppData \ Local \ Programs \ Python \ Python 38 \ lib \ site packages \ kiwisolver \ **init**. py" appears, line 8, in from ._cext import ( ImportError: DLL load failed while importing _cext: The specified module cannot be found. This error occurs. You can try installing this library to fix the problem [aka.ms/vs/17/release/vc_redist.x64.exe](https://aka.ms/vs/17/release/vc_redist.x64.exe)
> 
> It worked, thank you so much.😊

meme_generator==0.0.19.1
请检查下此包是不是这个版本，如果是这个版本还是报错那就再降版本

**Comment by ngc660sec** [comment]
> If the file "C: \ Users \ GWF \ AppData \ Local \ Programs \ Python \ Python 38 \ lib \ site packages \ kiwisolver \ **init**. py" appears, line 8, in from ._cext import ( ImportError: DLL load failed while importing _cext: The specified module cannot be found. This error occurs. You can try installing this library to fix the problem https://aka.ms/vs/17/release/vc_redist.x64.exe

如果你也是这个相同的报错请按照我说的步骤解决

**Comment by ZAZ7777** [comment]
执行 pip install msvc-runtime

**Comment by ngc660sec** [comment]
根据研究 是因为缺少VC库 可以注释meme包以及表情包功能

**Comment by ngc660sec** [comment]
或者查看此文章，或者输入以下命令

文章：https://blog.csdn.net/makesomethings/article/details/139807218
命令：pip install msvc-runtime
