### ISSUE TITLE
ModuleNotFoundError: No module named 'sparkai.llm'

### ISSUE THREAD

**Issue by long3012218885** [ngc660sec/NGCBot#74]
F:\python_obj\wx-bot\NGCBot>uv run main.py
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from BotServer.MainServer import MainServer
  File "F:\python_obj\wx-bot\NGCBot\BotServer\MainServer.py", line 1, in <module>
    from BotServer.MsgHandleServer.FriendMsgHandle import FriendMsgHandle
  File "F:\python_obj\wx-bot\NGCBot\BotServer\MsgHandleServer\FriendMsgHandle.py", line 2, in <module>
    from ApiServer.AiServer.AiDialogue import AiDialogue
  File "F:\python_obj\wx-bot\NGCBot\ApiServer\AiServer\AiDialogue.py", line 5, in <module>
    from sparkai.llm.llm import ChatSparkLLM, ChunkPrintHandler
ModuleNotFoundError: No module named 'sparkai.llm'

**Comment by long3012218885** [comment]
![image](https://github.com/user-attachments/assets/a489b8ed-3239-498e-bb0a-1d2ae65313ef)
这是vscode代码
![image](https://github.com/user-attachments/assets/c38ffadd-eeb6-48c8-ae4a-4a8c0d45b585)
这个是依赖版本，python版本是3.8.16
系统：win11

**Comment by ngc660sec** [comment]
> F:\python_obj\wx-bot\NGCBot>uv run main.py Traceback (most recent call last): File "main.py", line 1, in from BotServer.MainServer import MainServer File "F:\python_obj\wx-bot\NGCBot\BotServer\MainServer.py", line 1, in from BotServer.MsgHandleServer.FriendMsgHandle import FriendMsgHandle File "F:\python_obj\wx-bot\NGCBot\BotServer\MsgHandleServer\FriendMsgHandle.py", line 2, in from ApiServer.AiServer.AiDialogue import AiDialogue File "F:\python_obj\wx-bot\NGCBot\ApiServer\AiServer\AiDialogue.py", line 5, in from sparkai.llm.llm import ChatSparkLLM, ChunkPrintHandler ModuleNotFoundError: No module named 'sparkai.llm'

卸载sparkai以及spark-ai-python，重装spark-ai-python
pip install spark-ai-python
